# Generated by Django 4.0.6 on 2022-08-11 19:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('totales', '0002_auxiliares_publicadores_regulares_delete_totales'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='auxiliares',
            options={'verbose_name': 'auxiliar', 'verbose_name_plural': 'auxiliares'},
        ),
        migrations.AlterModelOptions(
            name='publicadores',
            options={'verbose_name': 'publicador', 'verbose_name_plural': 'publicadores'},
        ),
        migrations.AlterModelOptions(
            name='regulares',
            options={'verbose_name': 'reuglar', 'verbose_name_plural': 'regulares'},
        ),
    ]
