# Generated by Django 4.0.6 on 2022-10-24 21:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('totales', '0004_rename_estudios_biblicos_auxiliares_estudios_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='auxiliares',
            options={'ordering': ['id'], 'verbose_name': 'auxiliar', 'verbose_name_plural': 'auxiliares'},
        ),
        migrations.AlterModelOptions(
            name='publicadores',
            options={'ordering': ['id'], 'verbose_name': 'publicador', 'verbose_name_plural': 'publicadores'},
        ),
        migrations.AlterModelOptions(
            name='regulares',
            options={'ordering': ['id'], 'verbose_name': 'reuglar', 'verbose_name_plural': 'regulares'},
        ),
    ]
