# Generated by Django 4.1.4 on 2023-12-28 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shared', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='congregacion',
            name='on_trial',
            field=models.BooleanField(default=False),
        ),
    ]
