# Generated by Django 4.0.6 on 2022-08-09 23:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Asistencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('año', models.IntegerField()),
                ('mes', models.CharField(choices=[('Enero', 'Enero'), ('Febrero', 'Febrero'), ('Marzo', 'Marzo'), ('Abril', 'Abril'), ('Mayo', 'Mayo'), ('Junio', 'Junio'), ('Julio', 'Julio'), ('Agosto', 'Agosto'), ('Septiembre', 'Septiembre'), ('Octubre', 'Octubre'), ('Noviembre', 'Noviembre'), ('Diciembre', 'Diciembre')], max_length=10)),
                ('e_cantidad', models.IntegerField(blank=True, null=True)),
                ('e_total', models.IntegerField(blank=True, null=True)),
                ('e_promedio', models.IntegerField(blank=True, null=True)),
                ('f_cantidad', models.IntegerField(blank=True, null=True)),
                ('f_total', models.IntegerField(blank=True, null=True)),
                ('f_promedio', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'asistencia',
                'verbose_name_plural': 'asistencia',
                'ordering': ['año'],
            },
        ),
    ]
