# Generated by Django 4.0.6 on 2022-10-09 16:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('asistencia', '0002_entre_semana_fin_de_semana_delete_asistencia'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='entre_semana',
            options={'ordering': ['id'], 'verbose_name': 'entre semana', 'verbose_name_plural': 'entre semana'},
        ),
        migrations.AlterModelOptions(
            name='fin_de_semana',
            options={'ordering': ['id'], 'verbose_name': 'fin de semana', 'verbose_name_plural': 'fin de semana'},
        ),
    ]
