# Generated by Django 4.2.23 on 2025-08-20 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asistencia', '0004_alter_entre_semana_mes_alter_fin_de_semana_mes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entre_semana',
            name='mes',
            field=models.ImageField(choices=[(1, 'Septiembre'), (2, 'Octubre'), (3, 'Noviembre'), (4, 'Diciembre'), (5, 'Enero'), (6, 'Febrero'), (7, 'Marzo'), (8, 'Abril'), (9, 'Mayo'), (10, 'Junio'), (11, 'Julio'), (12, 'Agosto')], upload_to=''),
        ),
        migrations.AlterField(
            model_name='fin_de_semana',
            name='mes',
            field=models.ImageField(choices=[(1, 'Septiembre'), (2, 'Octubre'), (3, 'Noviembre'), (4, 'Diciembre'), (5, 'Enero'), (6, 'Febrero'), (7, 'Marzo'), (8, 'Abril'), (9, 'Mayo'), (10, 'Junio'), (11, 'Julio'), (12, 'Agosto')], upload_to=''),
        ),
    ]
