# Generated by Django 5.2.5 on 2025-08-27 23:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('publicador', '0016_alter_publicador_a_sm_alter_publicador_contacto_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Informe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('año', models.IntegerField()),
                ('mes', models.IntegerField(choices=[(1, 'Enero'), (2, 'Febrero'), (3, 'Marzo'), (4, 'Abril'), (5, 'Mayo'), (6, 'Junio'), (7, 'Julio'), (8, 'Agosto'), (9, 'Septiembre'), (10, 'Octubre'), (11, 'Noviembre'), (12, 'Diciembre')])),
                ('participacion', models.CharField(choices=[('Si', 'Si'), ('No', 'No')], max_length=2)),
                ('estudios', models.IntegerField(blank=True, default=0, null=True)),
                ('auxiliar', models.CharField(blank=True, choices=[('Si', 'Si'), ('No', 'No')], max_length=2, null=True)),
                ('horas', models.IntegerField(blank=True, default=0, null=True)),
                ('notas', models.CharField(blank=True, choices=[('Trabajos Construccion Salon', 'Trabajos construccion Salon'), ('Enfermo', 'Enfermo'), ('Cuidado fliar. enfermo', 'Cuidado fliar. enfermo'), ('Reactivado', 'Reactivado'), ('Trabajos en Asamblea', 'Trabajos en Asamblea'), ('Escuela Precursor', 'Escuela Precursor'), ('Inicia Regular', 'Inicia Regular'), ('Nuevo Publicador', 'Nuevo Publicador'), ('Bautismo', 'Bautismo'), ('Readmitido', 'Readmitido')], max_length=40, null=True)),
                ('servicio', models.CharField(choices=[('Publicador', 'Publicador'), ('Auxiliar', 'Auxiliar'), ('Regular', 'Regular'), ('Especial', 'Especial'), ('Misionero', 'Misionero')], max_length=10)),
                ('publicador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='informes', to='publicador.publicador')),
            ],
            options={
                'verbose_name': 'informe',
                'verbose_name_plural': 'informes',
                'ordering': ['id'],
                'unique_together': {('publicador', 'año', 'mes')},
            },
        ),
    ]
