# Generated by Django 4.0.6 on 2022-08-09 02:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('publicador', '0002_alter_publicador_a_sm_alter_publicador_regular'),
    ]

    operations = [
        migrations.CreateModel(
            name='Informe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('año', models.IntegerField()),
                ('mes', models.CharField(choices=[('Enero', 'Enero'), ('Febrero', 'Febrero'), ('Marzo', 'Marzo'), ('Abril', 'Abril'), ('Mayo', 'Mayo'), ('Junio', 'Junio'), ('Julio', 'Julio'), ('Agosto', 'Agosto'), ('Septiembre', 'Septiembre'), ('Octubre', 'Octubre'), ('Noviembre', 'Noviembre'), ('Diciembre', 'Diciembre')], max_length=10)),
                ('publicaciones', models.IntegerField(blank=True, null=True)),
                ('videos', models.IntegerField(blank=True, null=True)),
                ('horas', models.IntegerField(blank=True, null=True)),
                ('revisitas', models.IntegerField(blank=True, null=True)),
                ('estudios_biblicos', models.IntegerField(blank=True, null=True)),
                ('notas', models.CharField(choices=[('Auxiliar', 'Auxiliar'), ('Inactivo', 'Inactivo'), ('Mudado', 'Mudado'), ('Construccion', 'Construccion'), ('Enfermo', 'Enfermo'), ('Expulsado', 'Expulsado'), ('Reactivado', 'Reactivado'), ('Asamblea', 'Asamblea'), ('Escuela Precursor', 'Escuela Precursor'), ('Inicia Regular', 'Inicia Regular'), ('Nuevo Publicador', 'Nuevo Publicador')], max_length=20)),
                ('publicador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='publicador.publicador')),
            ],
            options={
                'verbose_name': 'informe',
                'verbose_name_plural': 'informes',
                'ordering': ['publicador'],
            },
        ),
    ]
