# Generated by Django 4.0.6 on 2022-08-09 02:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('informe', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='informe',
            name='horas',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='informe',
            name='notas',
            field=models.CharField(blank=True, choices=[('Auxiliar', 'Auxiliar'), ('Inactivo', 'Inactivo'), ('Mudado', 'Mudado'), ('Construccion', 'Construccion'), ('Enfermo', 'Enfermo'), ('Expulsado', 'Expulsado'), ('Reactivado', 'Reactivado'), ('Asamblea', 'Asamblea'), ('Escuela Precursor', 'Escuela Precursor'), ('Inicia Regular', 'Inicia Regular'), ('Nuevo Publicador', 'Nuevo Publicador')], max_length=20, null=True),
        ),
    ]
