# Generated by Django 4.0.6 on 2022-10-24 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('informe', '0003_rename_estudios_biblicos_informe_estudios'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='informe',
            options={'ordering': ['id'], 'verbose_name': 'informe', 'verbose_name_plural': 'informes'},
        ),
        migrations.AddField(
            model_name='informe',
            name='servicio',
            field=models.CharField(choices=[('Auxiliar', 'Auxiliar'), ('Publicador', 'Publicador'), ('Regular', 'Regular')], default='Publicador', max_length=10),
        ),
        migrations.AlterField(
            model_name='informe',
            name='estudios',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='informe',
            name='notas',
            field=models.CharField(blank=True, choices=[('Auxiliar', 'Auxiliar'), ('Inactivo', 'Inactivo'), ('Mudado', 'Mudado'), ('Construccion', 'Construccion'), ('Enfermo', 'Enfermo'), ('Expulsado', 'Expulsado'), ('Reactivado', 'Reactivado'), ('Asamblea', 'Asamblea'), ('Escuela Precursor', 'Escuela Precursor'), ('Inicia Regular', 'Inicia Regular'), ('Nuevo Publicador', 'Nuevo Publicador'), ('Bautismo', 'Bautismo'), ('Readmitido', 'Readmitido')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='informe',
            name='publicaciones',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='informe',
            name='revisitas',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='informe',
            name='videos',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
