# Generated by Django 4.1.3 on 2023-11-12 01:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('informe', '0004_alter_informe_options_informe_servicio_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='informe',
            name='publicaciones',
        ),
        migrations.RemoveField(
            model_name='informe',
            name='revisitas',
        ),
        migrations.RemoveField(
            model_name='informe',
            name='videos',
        ),
        migrations.AddField(
            model_name='informe',
            name='auxiliar',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='informe',
            name='participacion',
            field=models.BooleanField(default=False),
        ),
    ]
