# Generated by Django 4.1.3 on 2023-11-12 02:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('informe', '0005_remove_informe_publicaciones_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='informe',
            name='auxiliar',
            field=models.CharField(choices=[('SI', 'SI'), ('NO', 'NO')], max_length=10),
        ),
        migrations.AlterField(
            model_name='informe',
            name='participacion',
            field=models.CharField(choices=[('SI', 'SI'), ('NO', 'NO')], max_length=10),
        ),
    ]
