# Generated by Django 4.1.3 on 2023-11-12 02:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('informe', '0006_alter_informe_auxiliar_alter_informe_participacion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='informe',
            name='auxiliar',
            field=models.BooleanField(),
        ),
    ]
