# Generated by Django 4.1.3 on 2023-11-12 03:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('informe', '0007_alter_informe_auxiliar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='informe',
            name='auxiliar',
            field=models.CharField(choices=[('Si', 'Si'), ('No', 'No')], default='No', max_length=10),
        ),
        migrations.AlterField(
            model_name='informe',
            name='participacion',
            field=models.CharField(choices=[('Si', 'Si'), ('No', 'No')], default='Si', max_length=10),
        ),
    ]
