# Generated by Django 4.1.4 on 2023-11-14 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('informe', '0009_alter_informe_auxiliar_alter_informe_notas_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='informe',
            name='auxiliar',
            field=models.CharField(choices=[(' ', ' '), ('Si', 'Si')], default=' ', max_length=10),
        ),
        migrations.AlterField(
            model_name='informe',
            name='participacion',
            field=models.CharField(choices=[(' ', ' '), ('Si', 'Si')], default=' ', max_length=10),
        ),
    ]
