# Generated by Django 5.2.5 on 2025-08-16 03:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('informe', '0010_alter_informe_auxiliar_alter_informe_participacion'),
        ('publicador', '0012_alter_publicador_user'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='informe',
            unique_together={('publicador', 'año', 'mes')},
        ),
    ]
