# Generated by Django 4.2.23 on 2025-08-18 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('informe', '0011_alter_informe_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='informe',
            name='mes',
            field=models.CharField(choices=[('Septiembre', 'Septiembre'), ('Octubre', 'Octubre'), ('Noviembre', 'Noviembre'), ('Diciembre', 'Diciembre'), ('Enero', 'Enero'), ('Febrero', 'Febrero'), ('Marzo', 'Marzo'), ('Abril', 'Abril'), ('Mayo', 'Mayo'), ('Junio', 'Junio'), ('Julio', 'Julio'), ('Agosto', 'Agosto')], max_length=10),
        ),
    ]
