# Generated by Django 4.2.23 on 2025-08-20 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('informe', '0013_remove_informe_servicio_alter_informe_notas'),
    ]

    operations = [
        migrations.AlterField(
            model_name='informe',
            name='mes',
            field=models.IntegerField(choices=[('Septiembre', 'Septiembre'), ('Octubre', 'Octubre'), ('Noviembre', 'Noviembre'), ('Diciembre', 'Diciembre'), ('Enero', 'Enero'), ('Febrero', 'Febrero'), ('Marzo', 'Marzo'), ('Abril', 'Abril'), ('Mayo', 'Mayo'), ('Junio', 'Junio'), ('Julio', 'Julio'), ('Agosto', 'Agosto')]),
        ),
        migrations.AlterField(
            model_name='informe',
            name='notas',
            field=models.CharField(blank=True, choices=[(' ', ' '), ('Trabajos Construccion Salon', 'Trabajos construccion Salon'), ('Enfermo', 'Enfermo'), ('Cuidado fliar. enfermo', 'Cuidado fliar. enfermo'), ('Reactivado', 'Reactivado'), ('Trabajos en Asamblea', 'Trabajos en Asamblea'), ('Escuela Precursor', 'Escuela Precursor'), ('Inicia Regular', 'Inicia Regular'), ('Nuevo Publicador', 'Nuevo Publicador'), ('Bautismo', 'Bautismo'), ('Readmitido', 'Readmitido')], max_length=40, null=True),
        ),
    ]
