# Generated by Django 4.2.23 on 2025-08-20 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('informe', '0014_alter_informe_mes_alter_informe_notas'),
    ]

    operations = [
        migrations.AlterField(
            model_name='informe',
            name='mes',
            field=models.IntegerField(choices=[(1, 'Septiembre'), (2, 'Octubre'), (3, 'Noviembre'), (4, 'Diciembre'), (5, 'Enero'), (6, 'Febrero'), (7, 'Marzo'), (8, 'Abril'), (9, 'Mayo'), (10, 'Junio'), (11, 'Julio'), (12, 'Agosto')]),
        ),
    ]
