# Generated by Django 4.2.23 on 2025-08-21 18:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('publicador', '0014_alter_publicador_estado'),
        ('informe', '0015_alter_informe_mes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='informe',
            name='publicador',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='informes', to='publicador.publicador'),
        ),
    ]
