# Generated by Django 5.2.5 on 2025-08-26 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('informe', '0018_alter_informe_auxiliar_alter_informe_notas_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='informe',
            name='auxiliar',
            field=models.CharField(choices=[('Si', 'Si')]),
        ),
        migrations.AlterField(
            model_name='informe',
            name='participacion',
            field=models.CharField(choices=[('Si', 'Si')]),
        ),
    ]
