# Generated by Django 5.2.5 on 2025-08-26 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('informe', '0019_alter_informe_auxiliar_alter_informe_participacion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='informe',
            name='auxiliar',
            field=models.CharField(blank=True, choices=[('Si', 'Si')], max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='informe',
            name='participacion',
            field=models.CharField(blank=True, choices=[('Si', 'Si')], max_length=2, null=True),
        ),
    ]
