# Generated by Django 5.2.5 on 2025-08-26 23:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('informe', '0020_alter_informe_auxiliar_alter_informe_participacion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='informe',
            name='mes',
            field=models.IntegerField(choices=[(1, 'Enero'), (2, 'Febrero'), (3, 'Marzo'), (4, 'Abril'), (5, 'Mayo'), (6, 'Junio'), (7, 'Julio'), (8, 'Agosto'), (9, 'Septiembre'), (10, 'Octubre'), (11, 'Noviembre'), (12, 'Diciembre')], max_length=10),
        ),
    ]
