# Generated by Django 5.2.5 on 2025-08-27 02:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('informe', '0021_alter_informe_mes'),
    ]

    operations = [
        migrations.AddField(
            model_name='informe',
            name='servicio',
            field=models.CharField(blank=True, choices=[('Publicador', 'Publicador'), ('Auxiliar', 'Auxiliar'), ('Regular', 'Regular'), ('Especial', 'Especial'), ('Misionero', 'Misionero')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='informe',
            name='mes',
            field=models.IntegerField(choices=[(1, 'Enero'), (2, 'Febrero'), (3, 'Marzo'), (4, 'Abril'), (5, 'Mayo'), (6, 'Junio'), (7, 'Julio'), (8, 'Agosto'), (9, 'Septiembre'), (10, 'Octubre'), (11, 'Noviembre'), (12, 'Diciembre')]),
        ),
    ]
