# Generated by Django 4.0.6 on 2022-08-09 01:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Publicador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('nacimiento', models.DateField(blank=True, null=True)),
                ('bautismo', models.DateField(blank=True, null=True)),
                ('sexo', models.CharField(choices=[('Mujer', 'Mujer'), ('Hombre', 'Hombre')], max_length=10)),
                ('u_oo', models.CharField(choices=[('Ungido', 'Ungido'), ('Otras Ovejas', 'Otras Ovejas')], default='Otras Ovejas', max_length=15)),
                ('a_sm', models.CharField(choices=[('Anciano', 'Anciano'), ('Siervo Ministerial', 'Siervo Ministerial')], max_length=20)),
                ('regular', models.CharField(choices=[('Precursor Regular', 'Precursor Regular')], max_length=20)),
                ('grupo', models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4')], max_length=1)),
                ('estado', models.CharField(choices=[('Activo', 'Activo'), ('Inactivo', 'Inactivo'), ('Mudado', 'Mudado'), ('Fallecido', 'Fallecido')], max_length=10)),
            ],
            options={
                'verbose_name': 'publicador',
                'verbose_name_plural': 'publicadores',
                'ordering': ['nombre'],
            },
        ),
    ]
