# Generated by Django 4.0.6 on 2022-08-09 01:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publicador', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publicador',
            name='a_sm',
            field=models.CharField(blank=True, choices=[('Anciano', 'Anciano'), ('Siervo Ministerial', 'Siervo Ministerial')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='publicador',
            name='regular',
            field=models.CharField(blank=True, choices=[('Precursor Regular', 'Precursor Regular')], max_length=20, null=True),
        ),
    ]
