# Generated by Django 4.1.4 on 2023-08-24 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publicador', '0004_alter_publicador_estado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publicador',
            name='grupo',
            field=models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7'), ('8', '8'), ('9', '9')], max_length=1),
        ),
    ]
