# Generated by Django 4.1.4 on 2023-09-27 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publicador', '0005_alter_publicador_grupo'),
    ]

    operations = [
        migrations.AddField(
            model_name='publicador',
            name='contacto',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='publicador',
            name='telefono',
            field=models.CharField(default=388, max_length=12),
        ),
        migrations.AddField(
            model_name='publicador',
            name='telefono_contacto',
            field=models.CharField(default=388, max_length=12),
        ),
    ]
