# Generated by Django 4.1.4 on 2023-09-27 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publicador', '0006_publicador_contacto_publicador_telefono_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='publicador',
            name='apellido',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
