# Generated by Django 4.1.3 on 2023-09-28 18:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('publicador', '0007_publicador_apellido'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='publicador',
            options={'ordering': ['apellido'], 'verbose_name': 'publicador', 'verbose_name_plural': 'publicadores'},
        ),
    ]
