# Generated by Django 4.1.3 on 2023-11-11 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publicador', '0008_alter_publicador_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='publicador',
            name='regular',
        ),
        migrations.AddField(
            model_name='publicador',
            name='servicio',
            field=models.CharField(blank=True, choices=[('Precursor Regular', 'Precursor Regular'), ('Precursor Especial', 'Precursor Especial'), ('Misionero', 'Misionero')], max_length=20, null=True),
        ),
    ]
