# Generated by Django 4.1.4 on 2025-07-04 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publicador', '0009_remove_publicador_regular_publicador_servicio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publicador',
            name='estado',
            field=models.CharField(choices=[('Activo', 'Activo'), ('Inactivo', 'Inactivo'), ('Baja', 'Baja'), ('Mudado', 'Mudado'), ('Expulsado', 'Expulsado'), ('Fallecido', 'Fallecido')], max_length=10),
        ),
    ]
