# Generated by Django 4.2.23 on 2025-08-18 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publicador', '0012_alter_publicador_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publicador',
            name='estado',
            field=models.CharField(choices=[('Activo', 'Activo'), ('Inactivo', 'Inactivo'), ('Baja', 'Baja')], max_length=10),
        ),
    ]
