# Generated by Django 4.2.23 on 2025-08-20 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publicador', '0013_alter_publicador_estado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publicador',
            name='estado',
            field=models.CharField(choices=[('Activo', 'Activo'), ('Inactivo', 'Inactivo'), ('Baja', 'Baja'), ('Mudado', 'Mudado'), ('Sacado', 'Sacado')], max_length=10),
        ),
    ]
