# Generated by Django 5.2.5 on 2025-08-25 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publicador', '0014_alter_publicador_estado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publicador',
            name='a_sm',
            field=models.CharField(blank=True, choices=[('Anciano', 'Anciano'), ('Siervo Ministerial', 'Siervo Ministerial')], default='', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='publicador',
            name='contacto',
            field=models.CharField(blank=True, default='', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='publicador',
            name='servicio',
            field=models.CharField(blank=True, choices=[('Precursor Regular', 'Precursor Regular'), ('Precursor Especial', 'Precursor Especial'), ('Misionero', 'Misionero')], default='', max_length=20, null=True),
        ),
    ]
