# Generated by Django 5.2.5 on 2025-08-26 23:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publicador', '0015_alter_publicador_a_sm_alter_publicador_contacto_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publicador',
            name='a_sm',
            field=models.CharField(blank=True, choices=[('Anciano', 'Anciano'), ('Siervo Ministerial', 'Siervo Ministerial')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='publicador',
            name='contacto',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='publicador',
            name='servicio',
            field=models.CharField(blank=True, choices=[('Precursor Regular', 'Precursor Regular'), ('Precursor Especial', 'Precursor Especial'), ('Misionero', 'Misionero')], max_length=20, null=True),
        ),
    ]
